#pragma once

// X-macro to have single source of truth
#define ALL_MOUSE_BUTTONS\
  X(mb1, GLFW_MOUSE_BUTTON_1)\
  X(mb2, GLFW_MOUSE_BUTTON_2)\
  X(mb3, GLFW_MOUSE_BUTTON_3)\
  X(mb4, GLFW_MOUSE_BUTTON_4)\
  X(mb5, GLFW_MOUSE_BUTTON_5)\
  X(mb6, GLFW_MOUSE_BUTTON_6)\
  X(mb7, GLFW_MOUSE_BUTTON_7)\
  X(mb8, GLFW_MOUSE_BUTTON_8)\
  X(mbLast, GLFW_MOUSE_BUTTON_LAST)\
  X(mbLeft, GLFW_MOUSE_BUTTON_LEFT)\
  X(mbRight, GLFW_MOUSE_BUTTON_RIGHT)\
  X(mbMiddle, GLFW_MOUSE_BUTTON_MIDDLE)\
